CREATE TABLE cabs (
	id              INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	number		VARCHAR(255) UNIQUE NOT NULL,
	driver_id 	INT NOT NULL,
	created_at      DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	updated_at      DATETIME NULL ON UPDATE CURRENT_TIMESTAMP, 
	FOREIGN KEY (driver_id) REFERENCES drivers (id) ON UPDATE CASCADE
);
